# Generated by Django 3.2.13 on 2022-06-01 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trashed', models.BooleanField(default=False)),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=75, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
